/*
 * This source file was generated by the Gradle 'init' task
 */
package cosc2658;

import cosc2658.adt.Vec2;

public class App {
  public static void main(String[] args) {
    Grid grid = new Grid(new Vec2(8, 8), new Vec2(0, 7), new Vec2(0, 0));

    // grid.setGridData(new Vec2(0, 0), true);
    // grid.drawMap();

    // int allPaths = grid.useDebug().findAllPaths();
    int allPaths = grid.findAllPaths();
    System.out.println("Total paths: " + allPaths);
  }
}
